[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cpal = "0.15.2"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
hound = "3.5.1"
